### ISSUE TITLE
ImportError: cannot import name 'DtypeArg' from 'pandas._typing' 

### ISSUE THREAD

**Issue by CLeaf1023** [AlessioGalluccio/FastFlow#4]
which version of python is used？

Traceback (most recent call last):
  File "main.py", line 7, in <module>
    from train import train
  File "/home/robin/cuiyajie/FastFlow-master/train.py", line 12, in <module>
    import neptune.new as neptune
  File "/home/robin/anaconda3/envs/patchcore/lib/python3.7/site-packages/neptune/__init__.py", line 27, in <module>
    from neptune.internal.api_clients import backend_factory
  File "/home/robin/anaconda3/envs/patchcore/lib/python3.7/site-packages/neptune/internal/api_clients/__init__.py", line 17, in <module>
    from neptune.internal.api_clients.hosted_api_clients.hosted_backend_api_client import (
  File "/home/robin/anaconda3/envs/patchcore/lib/python3.7/site-packages/neptune/internal/api_clients/hosted_api_clients/hosted_backend_api_client.py", line 40, in <module>
    from neptune.internal.api_clients.hosted_api_clients.hosted_alpha_leaderboard_api_client import (
  File "/home/robin/anaconda3/envs/patchcore/lib/python3.7/site-packages/neptune/internal/api_clients/hosted_api_clients/hosted_alpha_leaderboard_api_client.py", line 37, in <module>
    from neptune.internal.api_clients.hosted_api_clients.mixins import HostedNeptuneMixin
  File "/home/robin/anaconda3/envs/patchcore/lib/python3.7/site-packages/neptune/internal/api_clients/hosted_api_clients/mixins.py", line 35, in <module>
    from neptune.utils import with_api_exceptions_handler
  File "/home/robin/anaconda3/envs/patchcore/lib/python3.7/site-packages/neptune/utils.py", line 30, in <module>
    import pandas as pd
  File "/home/robin/anaconda3/envs/patchcore/lib/python3.7/site-packages/pandas/__init__.py", line 142, in <module>
    from pandas.io.api import (
  File "/home/robin/anaconda3/envs/patchcore/lib/python3.7/site-packages/pandas/io/api.py", line 8, in <module>
    from pandas.io.excel import ExcelFile, ExcelWriter, read_excel
  File "/home/robin/anaconda3/envs/patchcore/lib/python3.7/site-packages/pandas/io/excel/__init__.py", line 1, in <module>
    from pandas.io.excel._base import ExcelFile, ExcelWriter, read_excel
  File "/home/robin/anaconda3/envs/patchcore/lib/python3.7/site-packages/pandas/io/excel/_base.py", line 32, in <module>
    from pandas.io.parsers import TextParser
  File "/home/robin/anaconda3/envs/patchcore/lib/python3.7/site-packages/pandas/io/parsers/__init__.py", line 1, in <module>
    from pandas.io.parsers.readers import (
  File "/home/robin/anaconda3/envs/patchcore/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 17, in <module>
    from pandas._typing import (
ImportError: cannot import name 'DtypeArg' from 'pandas._typing' (/home/robin/anaconda3/envs/patchcore/lib/python3.7/site-packages/pandas/_typing.py)

**Comment by AlessioGalluccio** [comment]
I used version 3.8 because it seems that it is required for Neptune to work
