### ISSUE TITLE
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same

### ISSUE THREAD

**Issue by CLeaf1023** [AlessioGalluccio/FastFlow#5]
Traceback (most recent call last):
  File "main.py", line 29, in <module>
    model = train(train_loader, test_loader)
  File "/home/robin/cuiyajie/FastFlow-master/train.py", line 65, in train
    model = FastFlow()
  File "/home/robin/cuiyajie/FastFlow-master/model.py", line 104, in __init__
    print(summary(self.feature_extractor, (3,384,384)))
  File "/home/robin/anaconda3/envs/patchcore/lib/python3.7/site-packages/torchsummary/torchsummary.py", line 72, in summary
    model(*x)
  File "/home/robin/anaconda3/envs/patchcore/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/robin/anaconda3/envs/patchcore/lib/python3.7/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/robin/anaconda3/envs/patchcore/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1071, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/robin/anaconda3/envs/patchcore/lib/python3.7/site-packages/timm/models/layers/patch_embed.py", line 35, in forward
    x = self.proj(x)
  File "/home/robin/anaconda3/envs/patchcore/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1071, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/robin/anaconda3/envs/patchcore/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 443, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/robin/anaconda3/envs/patchcore/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 440, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same

**Comment by simo-an** [comment]
update code to this in model.py
```python
            self.feature_extractor.to(c.device)
            print(summary(self.feature_extractor, (3,256,256), device=c.device))
```

**Comment by AlessioGalluccio** [comment]
Thank you very much, I changed the code. Let me know if you still have this problem
